name: Firebase Rules Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Firebase security rule tests
        run: pnpm exec firebase emulators:exec --project demo-sonl --only firestore,storage "pnpm vitest run tests/rules.spec.ts"
