name: Lighthouse CI

on:
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Serve production build
        run: |
          npx http-server dist -p 4173 &
          SERVER_PID=$!
          echo "SERVER_PID=$SERVER_PID" >> "$GITHUB_ENV"
          sleep 5

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:4173
          configPath: ./.lighthouserc.json
          uploadArtifacts: true

      - name: Stop HTTP server
        if: always()
        run: |
          if [ -n "${SERVER_PID}" ]; then
            kill ${SERVER_PID} || true
          fi
